export const BUILD_CATEGORIES = [
  {
    id: 'motorcycles',
    label: 'Motorcycles',
    icon: '🏍️',
    partCategories: [
      'Engine',
      'Exhaust',
      'Suspension',
      'Wheels & Tires',
      'Front End',
      'Frame & Body',
      'Controls',
      'Electrical',
      'Paint & Finish',
    ],
  },
  {
    id: 'cars',
    label: 'Cars',
    icon: '🚗',
    partCategories: [
      'Engine & Drivetrain',
      'Exhaust',
      'Suspension & Brakes',
      'Wheels & Tires',
      'Exterior & Body',
      'Interior',
      'Audio & Electronics',
      'Paint & Wrap',
    ],
  },
  {
    id: 'bicycles',
    label: 'Bicycles',
    icon: '🚲',
    partCategories: [
      'Drivetrain',
      'Brakes',
      'Wheels & Tires',
      'Handlebars & Cockpit',
      'Frame & Fork',
      'Saddle & Seatpost',
      'Lighting & Electronics',
      'Paint & Finish',
    ],
  },
  {
    id: 'drones',
    label: 'Drones',
    icon: '🚁',
    partCategories: [
      'Frame',
      'Motors & ESCs',
      'Flight Controller',
      'Camera & Gimbal',
      'Battery & Power',
      'Radio & Receiver',
      'Props',
      'FPV & Video',
    ],
  },
  {
    id: 'pc_gaming',
    label: 'PC / Gaming',
    icon: '🖥️',
    partCategories: [
      'CPU & Cooling',
      'GPU',
      'Motherboard & RAM',
      'Storage',
      'Case & Airflow',
      'Power Supply',
      'Peripherals',
      'RGB & Mods',
    ],
  },
  {
    id: 'audio_hifi',
    label: 'Audio / Hi-Fi',
    icon: '🎵',
    partCategories: [
      'Source & DAC',
      'Amplifier',
      'Speakers',
      'Headphones',
      'Cables & Interconnects',
      'Turntable & Vinyl',
      'Room Treatment',
      'Power & Conditioning',
    ],
  },
  {
    id: 'cameras',
    label: 'Cameras',
    icon: '📷',
    partCategories: [
      'Camera Body',
      'Lenses',
      'Stabilization & Gimbals',
      'Lighting',
      'Audio & Mics',
      'Storage & Media',
      'Bags & Straps',
      'Filters & Accessories',
      'Monitors & Displays',
      'Power & Batteries',
    ],
  },
  {
    id: 'guitars',
    label: 'Guitars',
    icon: '🎸',
    partCategories: [
      'Body & Neck',
      'Pickups',
      'Bridge & Hardware',
      'Tuners',
      'Electronics & Controls',
      'Strings',
      'Strap & Accessories',
      'Paint & Finish',
    ],
  },
  {
    id: '3d_printing',
    label: '3D Printing',
    icon: '🖨️',
    partCategories: [
      'Frame & Motion',
      'Hotend & Extruder',
      'Heated Bed',
      'Electronics & Control',
      'Enclosure & Mods',
      'Filament & Materials',
      'Post-Processing',
    ],
  },
  {
    id: 'camping',
    label: 'Camping / Outdoor',
    icon: '⛺',
    partCategories: [
      'Shelter & Sleep',
      'Cooking & Fire',
      'Lighting',
      'Navigation & Safety',
      'Clothing & Layering',
      'Pack & Carry',
      'Water & Filtration',
      'Tools & Gear',
    ],
  },
]

export type BuildCategory = typeof BUILD_CATEGORIES[number]['id']
